# Generated by Django 3.0.7 on 2020-10-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('usermedia', '0002_auto_20200706_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to='usermedia.UserMedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='account.UserProfile')),
            ],
        ),
    ]
