# Generated by Django 3.0.7 on 2020-07-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='token',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='token',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
    ]
