# Generated by Django 3.0.7 on 2020-07-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200705_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='has_contact',
            field=models.BooleanField(default=False),
        ),
    ]
