# Generated by Django 3.0.6 on 2020-05-28 16:31

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('male', 'Man'), ('female', 'Woman')], db_index=True, default='male', max_length=6, verbose_name='Gender')),
                ('publicname', models.CharField(default='', max_length=250)),
                ('is_online', models.BooleanField(default=False)),
                ('account', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
