# Generated by Django 3.0.7 on 2020-10-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
