# Generated by Django 3.0.6 on 2020-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socketconnection',
            name='token',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True),
        ),
    ]
