# Generated by Django 3.0.6 on 2020-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20200702_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketconnection',
            name='sid',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socketconnection',
            name='token',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
