# Generated by Django 3.0.7 on 2020-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Alias')),
                ('name', models.CharField(help_text='Name', max_length=100)),
            ],
        ),
    ]
