# Generated by Django 3.0.7 on 2020-07-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='ru', help_text='Language', max_length=5)),
                ('level', models.IntegerField(default='3', help_text='Level')),
                ('tp', models.CharField(default='questionend', help_text='Mode of quize', max_length=12)),
                ('mode', models.CharField(default='fullmatch', help_text='Type of matching', max_length=10)),
                ('question', models.TextField(verbose_name='Question')),
                ('answers', models.TextField(default='', help_text='Divided by coma', verbose_name='Answers')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default='1', help_text='Order')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Theme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.UserProfile', verbose_name='User')),
            ],
        ),
    ]
