# Generated by Django 3.0.7 on 2020-08-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_room_roommessage_roomquestion_roomusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomusers',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomusers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_question_text',
        ),
        migrations.RemoveField(
            model_name='room',
            name='question_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='questions_json',
        ),
        migrations.RemoveField(
            model_name='room',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='room',
            name='winner',
        ),
        migrations.AlterField(
            model_name='room',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Question', verbose_name='Cur question'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('questionend', 'Till questions are fineshed.'), ('infinite', 'Infinite quize (looping over questions).'), ('custom', 'Custom. Defining question by author.')], default='infinite', max_length=50, verbose_name='Quiz type'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='RoomUsers',
        ),
    ]
