# Generated by Django 3.0.7 on 2020-08-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200801_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roommessage',
            name='question',
        ),
    ]
