# Generated by Django 3.0.9 on 2020-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_roommessagesmile_roommessagesticker_smile_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smile',
            name='smile',
            field=models.URLField(max_length=50, verbose_name='URL Smile'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='sticker',
            field=models.URLField(max_length=50, verbose_name='URL Sticker'),
        ),
    ]
