# Generated by Django 3.0.7 on 2020-07-06 12:23

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '80x80', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='user_photo'),
        ),
    ]
