# Generated by Django 3.0.7 on 2020-10-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0002_auto_20200706_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
