# Generated by Django 3.0.7 on 2020-10-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0004_auto_20201017_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
