# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 08:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='\u041e\u0442\u0432\u0435\u0442\u044b')),
            ],
        ),
    ]
