# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180128_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='\u041f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c')),
                ('name', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.Theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(default='', help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(help_text='\u041f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c (\u0434\u043b\u044f \u0438\u043c\u0435\u043d \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u043e\u0432 \u0441 \u0434\u0430\u043d\u043d\u044b\u043c\u0438)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
    ]
