# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180128_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_time', models.DateTimeField()),
                ('current_question', django.contrib.postgres.fields.jsonb.JSONField(help_text='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0442\u0435\u043a\u0443\u0449\u0435\u043c \u0432\u043e\u043f\u0440\u043e\u0441\u0435 (\u0442\u0435\u043a\u0441\u0442, id, \u043f\u043e\u0440\u044f\u0434\u043a\u043e\u0432\u044b\u0439 \u043d\u043e\u043c\u0435\u0440)', verbose_name='\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0432\u043e\u043f\u0440\u043e\u0441')),
                ('question_set', django.contrib.postgres.fields.jsonb.JSONField(help_text='\u0421\u043f\u0438\u0441\u043e\u043a \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u0432\u0438\u043a\u0442\u043e\u0440\u0438\u043d\u044b', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u0432\u0438\u043a\u0442\u043e\u0440\u0438\u043d\u044b')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
