# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_openedquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openedquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.DeleteModel(
            name='OpenedQuiz',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
