# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 14:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20180128_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='\u041e\u0442\u0432\u0435\u0442\u044b')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='\u041f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c')),
                ('name', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100)),
                ('questions', models.ManyToManyField(to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('time', '\u041f\u043e \u0432\u0440\u0435\u043c\u0435\u043d\u0438'), ('score', '\u041f\u043e \u043e\u0447\u043a\u0430\u043c'), ('end', '\u0414\u043e \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0432\u043e\u043f\u0440\u043e\u0441\u0430'), ('infinite', '\u0411\u0435\u0441\u043a\u043e\u043d\u0435\u0447\u043d\u0430\u044f')], default='score', max_length=10, verbose_name='\u0422\u0438\u043f \u0438\u0433\u0440\u044b')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_time', models.DateTimeField()),
                ('answers', models.TextField(verbose_name='\u041e\u0442\u0432\u0435\u0442\u044b \u043d\u0430 \u0442\u0435\u043a\u0443\u0449\u0438\u0439 \u0432\u043e\u043f\u0440\u043e\u0441')),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(help_text='\u0412\u0441\u0435 \u043f\u043e \u043a\u043e\u043c\u043d\u0430\u0442\u0435', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u0432\u0438\u043a\u0442\u043e\u0440\u0438\u043d\u044b')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomQuiestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('quiestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='\u041f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c (\u0434\u043b\u044f \u0438\u043c\u0435\u043d \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u043e\u0432 \u0441 \u0434\u0430\u043d\u043d\u044b\u043c\u0438)')),
                ('name', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.RoomQuiestion', verbose_name='\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0432\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AddField(
            model_name='room',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u0431\u0435\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Theme'),
        ),
    ]
