# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180130_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lang',
            field=models.CharField(default='ru', help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(unique=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
    ]
