# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='token',
            field=models.CharField(db_index=True, help_text='\u0422\u043e\u043a\u0435\u043d', max_length=100),
        ),
    ]
