# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20180205_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='token',
        ),
        migrations.AddField(
            model_name='room',
            name='token',
            field=models.CharField(db_index=True, default='', help_text='\u0422\u043e\u043a\u0435\u043d', max_length=100),
            preserve_default=False,
        ),
    ]
