# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20180206_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomquiestion',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.Room', verbose_name='Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='current_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current question'),
        ),
        migrations.AlterField(
            model_name='roomquiestion',
            name='quiestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='Question'),
        ),
    ]
