# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20180206_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomquestion',
            name='order',
        ),
    ]
