# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20180206_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='json_data',
        ),
        migrations.AddField(
            model_name='room',
            name='questions_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='\u0412\u0441\u0435 \u043f\u043e \u043a\u043e\u043c\u043d\u0430\u0442\u0435', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432'),
        ),
    ]
