# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20180206_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_question_text',
            field=models.TextField(default='', verbose_name='\u0432\u043e\u043f\u0440\u043e\u0441'),
            preserve_default=False,
        ),
    ]
