# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20180206_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
    ]
