# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 12:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_roommessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='\u041e\u0442\u0432\u0435\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='room',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='\u041e\u0442\u0432\u0435\u0442\u044b \u043d\u0430 \u0442\u0435\u043a\u0443\u0449\u0438\u0439 \u0432\u043e\u043f\u0440\u043e\u0441'),
        ),
    ]
