# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20180207_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomusers',
            name='score',
            field=models.IntegerField(default=0, verbose_name='\u0421\u0447\u0435\u0442'),
        ),
    ]
