# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_roomusers_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_active',
            new_name='is_done',
        ),
    ]
