# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20180216_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tp',
            field=models.CharField(default='fullmatch', help_text='Type of matching', max_length=10),
        ),
    ]
