# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_question_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lang',
            field=models.CharField(default='ru', help_text='Language', max_length=5),
        ),
    ]
