# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20180221_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.CharField(default='', help_text='Divided by coma', max_length=250, verbose_name='Answers'),
        ),
    ]
