# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20180227_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='answers',
            field=models.CharField(default='', help_text='Divided by coma', max_length=250, verbose_name='Answers'),
        ),
    ]
