# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20180227_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_en',
            field=models.CharField(default='', help_text='Divided by coma', max_length=250, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers_ru',
            field=models.CharField(default='', help_text='Divided by coma', max_length=250, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True, unique=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_ru',
            field=models.TextField(null=True, unique=True, verbose_name='Question'),
        ),
    ]
