# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20180227_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
    ]
