# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20180228_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(default='', help_text='Divided by coma', verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_en',
            field=models.TextField(default='', help_text='Divided by coma', null=True, verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_ru',
            field=models.TextField(default='', help_text='Divided by coma', null=True, verbose_name='Answers'),
        ),
    ]
