# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20180228_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
