# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_roommessage_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name_en',
            field=models.CharField(help_text='Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name_ru',
            field=models.CharField(help_text='Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_en',
            field=models.CharField(help_text='Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_ru',
            field=models.CharField(help_text='Name', max_length=100, null=True),
        ),
    ]
