# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
