# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_question_is_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_edit',
        ),
    ]
