# Generated by Django 3.0.7 on 2020-10-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_user', to='account.UserProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_owner', to='account.UserProfile')),
            ],
        ),
    ]
